package:
    name: eman2
    version: 2.21

source:
    path: {{ RECIPE_DIR }}/../..

requirements:
    {% set reqs_common = [                         
    "defaults::appnope     0.1.0 py27hb466136_0",  # [osx]      
    "defaults::backports     1.0 py27hb4f9756_1",  # [osx]        
    "defaults::backports.functools_lru_cache     1.4 py27h2aca819_1",  # [osx]        
    "defaults::backports.shutil_get_terminal_size     1.0.0 py27hc9115de_2",  # [osx]      
    "defaults::backports_abc     0.5 py27h6972548_0",  # [osx]        
    "conda forge::boost        1.63.0 py27_5",  # [osx]          
    "conda forge::boost cpp        1.63.0 2",  # [osx]               
    "defaults::bsddb     1.0 py27_1",  # [osx]                
    "defaults::bzip2     1.0.6 hd86a083_4",  # [osx]          
    "defaults::ca certificates     2017.08.26 ha1e5d58_0",  # [osx]     
    "defaults::cctools     895 h7512d6f_0",  # [osx]            
    "defaults::certifi     2018.1.18 py27_0",  # [osx]          
    "defaults::clang     4.0.1 h662ec87_0",  # [osx]          
    "defaults::clang_osx 64     4.0.1 h1ce6c1d_8",  # [osx]          
    "defaults::clangxx     4.0.1 hc9b4283_0",  # [osx]          
    "defaults::clangxx_osx 64     4.0.1 h22b1bf0_8",  # [osx]          
    "defaults::compiler rt     4.0.1 h5487866_0",  # [osx]          
    "defaults::cycler     0.10.0 py27hfc73c78_0",  # [osx]     
    "defaults::db     5.3.28 1",  # [osx]                  
    "defaults::decorator     4.2.1 py27_0",  # [osx]              
    "defaults::enum34     1.1.6 py27hf475452_1",  # [osx]      
    "cryoem::fftw mpi   3.3.6 2",  # [osx]                     
    "defaults::freetype     2.8 h12048fb_1",  # [osx]            
    "cryoem::ftgl   2.1.3 1",  # [osx]                     
    "defaults::functools32     3.2.3.2 py27h8ceab06_1",  # [osx]    
    "defaults::gsl     2.2.1 h002c638_3",  # [osx]          
    "defaults::hdf5     1.8.18 h017327d_1",  # [osx]         
    "defaults::icu     58.2 h4b95b61_1",  # [osx]           
    "defaults::intel openmp     2018.0.0 h8158457_8",  # [osx]       
    "defaults::ipython     5.4.1 py27_2",  # [osx]              
    "defaults::ipython_genutils     0.2.0 py27h8b9a179_0",  # [osx]      
    "defaults::jpeg     9b he5867d9_2",  # [osx]             
    "defaults::ld64     274.2 h7c2db76_0",  # [osx]          
    "defaults::libcxx     4.0.1 h579ed51_0",  # [osx]          
    "defaults::libcxxabi     4.0.1 hebd6815_0",  # [osx]          
    "defaults::libedit     3.1 hb4e282d_0",  # [osx]            
    "defaults::libffi     3.2.1 h475c297_4",  # [osx]          
    "defaults::libgfortran     3.0.1 h93005f0_2",  # [osx]          
    "defaults::libgpuarray     0.6.9 0",  # [osx]                   
    "defaults::libpng     1.6.32 hd1e8b91_4",  # [osx]         
    "defaults::libtiff     4.0.9 h0dac147_0",  # [osx]          
    "defaults::llvm     4.0.1 hc748206_0",  # [osx]          
    "defaults::llvm lto tapi     4.0.1 h6701bc3_0",  # [osx]          
    "defaults::mako     1.0.7 py27h07f8f8b_0",  # [osx]      
    "defaults::markupsafe     1.0 py27hd3c86fa_1",  # [osx]        
    "defaults::matplotlib     2.1.2 py27h6d6146d_0",  # [osx]      
    "defaults::mkl     2018.0.1 hfbd8650_4",  # [osx]       
    "defaults::mkl service     1.1.2 py27hcba3029_4",  # [osx]      
    "defaults::ncurses     6.0 hd04f020_2",  # [osx]            
    "defaults::nose     1.3.7 py27h2ee3cb8_2",  # [osx]      
    "defaults::numpy     1.9.3 py27hb3dd696_3",  # [osx]      
    "cryoem::openmpi   2.0.2 0",  # [osx]                     
    "defaults::openssl     1.0.2n hdbc3d79_0",  # [osx]         
    "defaults::pathlib2     2.3.0 py27he09da1e_0",  # [osx]      
    "defaults::pexpect     4.3.1 py27_0",  # [osx]              
    "defaults::pickleshare     0.7.4 py27h37e3d41_0",  # [osx]      
    "defaults::pip     9.0.1 py27h1567d89_4",  # [osx]      
    "defaults::prompt_toolkit     1.0.15 py27h4a7b9c2_0",  # [osx]     
    "defaults::ptyprocess     0.5.2 py27h70f6364_0",  # [osx]      
    "cryoem::pydusa   1.15 np19_9",  # [osx]                 
    "defaults::pygments     2.2.0 py27h1a556bb_0",  # [osx]      
    "defaults::pygpu     0.6.9 py27_0",  # [osx]              
    "conda forge::pyopengl        3.1.0 py27_0",  # [osx]           
    "defaults::pyparsing     2.2.0 py27h5bb6aaf_0",  # [osx]      
    "defaults::pyqt     4.11.4 py27_4",  # [osx]             
    "defaults::python     2.7.14 hde5916a_29",  # [osx]        
    "defaults::python dateutil     2.6.1 py27hd56c96b_1",  # [osx]      
    "defaults::pytz     2017.3 py27h803c07a_0",  # [osx]     
    "defaults::qt     4.8.7 4",  # [osx]                   
    "defaults::readline     7.0 hc1231fa_4",  # [osx]            
    "defaults::scandir     1.6 py27h97aa1ee_0",  # [osx]        
    "defaults::scikit learn     0.19.1 py27h9788993_0",  # [osx]     
    "defaults::scipy     1.0.0 py27h793f721_0",  # [osx]      
    "defaults::setuptools     38.4.0 py27_0",  # [osx]             
    "defaults::simplegeneric     0.8.1 py27_2",  # [osx]              
    "defaults::singledispatch     3.4.0.3 py27he22c18d_0",  # [osx]    
    "defaults::sip     4.18 py27_0",  # [osx]               
    "defaults::six     1.11.0 py27h7252ba3_1",  # [osx]     
    "defaults::sqlite     3.22.0 h3efe00b_0",  # [osx]         
    "defaults::ssl_match_hostname     3.5.0.1 py27h8780752_2",  # [osx]    
    "defaults::subprocess32     3.2.7 py27h24b2887_0",  # [osx]      
    "defaults::theano     0.9.0 py27h5762e8c_3",  # [osx]      
    "defaults::tk     8.6.7 h35a86e2_3",  # [osx]          
    "defaults::tornado     4.5.3 py27_0",  # [osx]              
    "defaults::traitlets     4.3.2 py27hcf08151_0",  # [osx]      
    "defaults::wcwidth     0.1.7 py27h817c265_0",  # [osx]      
    "defaults::wheel     0.30.0 py27h677a027_1",  # [osx]     
    "defaults::xz     5.2.3 h0278029_2",  # [osx]          
    "defaults::zlib     1.2.11 hf3cbc9b_2",  # [osx]         
    
    
        "defaults::backports                          1.0 py27h63c9359_1",    # [linux]       
        "defaults::backports.shutil_get_terminal_size 1.0.0 py27h5bc021e_2",    # [linux]     
        "defaults::binutils_impl_linux 64             2.28.1 h04c84fa_2",    # [linux]        
        "defaults::binutils_linux 64                  7.2.0 25",    # [linux]                 
        "conda forge::boost                              1.63.0 py27_5",    # [linux]         
        "conda forge::boost cpp                          1.63.0 2",    # [linux]              
        "defaults::bsddb                              1.0 py27_1",    # [linux]               
        "defaults::bzip2                              1.0.6 h9a117a8_4",    # [linux]         
        "defaults::ca certificates                    2017.08.26 h1d4fec5_0",    # [linux]    
        "defaults::cairo                              1.12.18 6",    # [linux]                
        "defaults::certifi                            2018.1.18 py27_0",    # [linux]         
        "defaults::db                                 5.3.28 1",    # [linux]                 
        "defaults::decorator                          4.2.1 py27_0",    # [linux]             
        "defaults::enum34                             1.1.6 py27h99a27e9_1",    # [linux]     
        "cryoem::fftw mpi                           3.3.6 2",    # [linux]                    
        "defaults::fontconfig                         2.11.1 6",    # [linux]                 
        "defaults::freetype                           2.5.5 1",    # [linux]                  
        "cryoem::ftgl                               2.1.3 1",    # [linux]                    
        "defaults::gcc_impl_linux 64                  7.2.0 hc5ce805_2",    # [linux]         
        "defaults::gcc_linux 64                       7.2.0 25",    # [linux]                 
        "defaults::gsl                                2.2.1 h0c605f7_3",    # [linux]         
        "defaults::gxx_impl_linux 64                  7.2.0 hd3faf3d_2",    # [linux]         
        "defaults::gxx_linux 64                       7.2.0 25",    # [linux]                 
        "defaults::hdf5                               1.8.18 h6792536_1",    # [linux]        
        "defaults::icu                                58.2 h9c2bf20_1",    # [linux]          
        "defaults::intel openmp                       2018.0.0 hc7b2577_8",    # [linux]      
        "defaults::ipython                            5.4.1 py27_2",    # [linux]             
        "defaults::ipython_genutils                   0.2.0 py27h89fb69b_0",    # [linux]     
        "defaults::jpeg                               9b h024ee3a_2",    # [linux]            
        "defaults::libedit                            3.1 heed3624_0",    # [linux]           
        "defaults::libffi                             3.2.1 hd88cf55_4",    # [linux]         
        "defaults::libgcc                             7.2.0 h69d50b8_2",    # [linux]         
        "defaults::libgcc ng                          7.2.0 h7cc24e2_2",    # [linux]         
        "defaults::libgfortran ng                     7.2.0 h9f7466a_2",    # [linux]         
        "defaults::libgpuarray                        0.6.9 0",    # [linux]                  
        "defaults::libpng                             1.6.17 0",    # [linux]                 
        "defaults::libstdcxx ng                       7.2.0 h7a57d05_2",    # [linux]         
        "defaults::libtiff                            4.0.9 h28f6b97_0",    # [linux]         
        "defaults::libxml2                            2.9.7 h26e45fe_0",    # [linux]         
        "defaults::mako                               1.0.7 py27h3d58d4b_0",    # [linux]     
        "defaults::markupsafe                         1.0 py27h97b2822_1",    # [linux]       
        "defaults::matplotlib                         1.4.3 np19py27_2",    # [linux]         
        "defaults::mkl                                2018.0.1 h19d6760_4",    # [linux]      
        "defaults::mkl service                        1.1.2 py27hb2d42c5_4",    # [linux]     
        "defaults::ncurses                            6.0 h9df7e31_2",    # [linux]           
        "defaults::nose                               1.3.7 py27heec2199_2",    # [linux]     
        "defaults::numpy                              1.9.3 py27h7e35acb_3",    # [linux]     
        "cryoem::openmpi                            2.0.2 0",    # [linux]                    
        "defaults::openssl                            1.0.2n hb7f436b_0",    # [linux]        
        "defaults::pathlib2                           2.3.0 py27h6e9d198_0",    # [linux]     
        "defaults::pexpect                            4.3.1 py27_0",    # [linux]             
        "defaults::pickleshare                        0.7.4 py27h09770e1_0",    # [linux]     
        "defaults::pip                                9.0.1 py27ha730c48_4",    # [linux]     
        "defaults::pixman                             0.32.6 0",    # [linux]                 
        "defaults::prompt_toolkit                     1.0.15 py27h1b593e1_0",    # [linux]    
        "defaults::ptyprocess                         0.5.2 py27h4ccb14c_0",    # [linux]     
        "defaults::py2cairo                           1.10.0 py27_2",    # [linux]            
        "cryoem::pydusa                             1.15 np19_9",    # [linux]                
        "defaults::pygments                           2.2.0 py27h4a8b6f5_0",    # [linux]     
        "defaults::pygpu                              0.6.9 py27_0",    # [linux]             
        "conda forge::pyopengl                           3.1.0 py27_0",    # [linux]          
        "defaults::pyparsing                          2.0.3 py27_0",    # [linux]             
        "defaults::pyqt                               4.11.4 py27_4",    # [linux]            
        "defaults::python                             2.7.14 h1571d57_29",    # [linux]       
        "defaults::python dateutil                    2.6.1 py27h4ca5741_1",    # [linux]     
        "defaults::pytz                               2017.3 py27h001bace_0",    # [linux]    
        "defaults::qt                                 4.8.7 3",    # [linux]                  
        "defaults::readline                           7.0 ha6073c6_4",    # [linux]           
        "defaults::scandir                            1.6 py27hf7388dc_0",    # [linux]       
        "defaults::scikit learn                       0.19.1 py27h445a80a_0",    # [linux]    
        "defaults::scipy                              1.0.0 py27hf5f0f52_0",    # [linux]     
        "defaults::setuptools                         38.4.0 py27_0",    # [linux]            
        "defaults::simplegeneric                      0.8.1 py27_2",    # [linux]             
        "defaults::sip                                4.18 py27_0",    # [linux]              
        "defaults::six                                1.11.0 py27h5f960f1_1",    # [linux]    
        "defaults::sqlite                             3.22.0 h1bed415_0",    # [linux]        
        "defaults::theano                             0.9.0 py27ha72280b_3",    # [linux]     
        "defaults::tk                                 8.6.7 hc745277_3",    # [linux]         
        "defaults::traitlets                          4.3.2 py27hd6ce930_0",    # [linux]     
        "defaults::wcwidth                            0.1.7 py27h9e3e1ab_0",    # [linux]     
        "defaults::wheel                              0.30.0 py27h2bc6bb2_1",    # [linux]    
        "defaults::xz                                 5.2.3 h55aa19d_2",    # [linux]         
        "defaults::zlib                               1.2.11 ha838bed_2",    # [linux]                 
        ] %}",
    
    build:
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}
    
    run:
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}

build:
  script_env:
   - EMAN_TEST_SKIP  # [osx]

test:
  requires:
    - openmpi              # [not win]
  
  source_files:
    - examples/mpi_test.py
    - tests/run_prog_tests.sh
    - tests/programs_no_test.txt
    - tests/test_EMAN2DIR.py
    - tests/run_tests.sh
    - tests/run_tests.bat

  commands:
    - bash tests/run_tests.sh                                # [not win]
    - call tests\run_tests.bat                               # [win]
